### ISSUE TITLE
Gorm unknown installation issue

### ISSUE THREAD

**Issue by Mwar22** [gnustep/apps-gorm#1]
Hi,

I have an unknown problem when installing gorm(1.2.20) on linux. I followed the instructions both from [www.gnustep.net](http://www.gnustep.net/Documentation/BuildGuide/develop.html), [gnustep.made-it.com](http://gnustep.made-it.com/BuildGuide/index.html#BUILDING.GNUSTEP),  and from the INSTALL file, but all these instructions failed. I tried to read the makefile, search for bugs and so on, but I could not find anything (maybe because I'm just a beginner). I'm getting the following errors on kali linux 2.0(debian):

<h5># * make && make install <br>
bash: ANNOUNCE: command not found.<br><br>

# make GNUSTEP_INSTALLATION_DIR="$GNUSTEP_SYSTEM_ROOT" install<br>
GNUmakefile:29: /common.make: Arquivo ou diretório não encontrado(File or directory not found)<br>
GNUmakefile:182: /aggregate.make: Arquivo ou diretório não encontrado<br>
GNUmakefile:183: /application.make: Arquivo ou diretório não encontrado<br>
make: *** No rule to make target '/application.make'.  Stop.
</h5>

ps: the first one is the instruction that is inside of INSTALL, but I noticed that "make" is doing something with all the files in the directory, and since I don't have any experience in makefiles(yet, maybe in some weeks...), there are nothing I cold do...

Thanks for the attention. I  (in the future, because I think I haven't enought programming experience yet) would like to help in this project :)

Att,
Lucas. from Brazil.

**Comment by gcasa** [comment]
These are both utterly ancient sources.  The most recent instructions on on
the wiki and on www.gnustep.org.

On Thursday, May 12, 2016, Mwar22 <notifications@github.com> wrote:

> Reopened #1 <https://github.com/gnustep/gorm/issues/1>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnustep/gorm/issues/1#event-658083741>
>


-- 
Gregory Casamento
GNUstep Lead Developer / OLC, Principal Consultant
http://www.gnustep.org - http://heronsperch.blogspot.com
http://ind.ie/phoenix/

**Comment by Mwar22** [comment]
Hi again,


Of course, I downloaded from www.gnustep.org, but the problem still remains. The older sites that i cited are, lets say, tentatives. What I don't know, is why the instructions contained in INSTALL doesn't work. 

Att,
Lucas.

**Comment by gcasa** [comment]
Try 

`make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM install`

**Comment by Mwar22** [comment]
Wow, this surprised me. It's unfortunate, but i cant replicate this error anymore (well, i mostly use arch nowadays so the issue is out of scope and this topic was for so long buried in the past ...that i don't have the energy for it anymore). Anyways, thanks for the answer, and good luck with the project.
