### ISSUE TITLE
No NSViewController class in class hierarchy

### ISSUE THREAD

**Issue by buzzdeee** [gnustep/apps-gorm#45]
Not sure if that's by some intent I'm not aware of, but NSViewController class is not showing up under its superclass NSResponder.
This is Gorm 1.3.1, OpenBSD 7.5, amd64 latest GNUstep releases.

**Comment by gcasa** [comment]
![controllers](https://github.com/user-attachments/assets/bce4186c-1377-4b1b-aa30-145e7286b757)

It's there on Linux... I will check on OpenBSD.   Gorm 1.3.1 was released a while ago, so I can only assume it wasn't there in that release.

**Comment by buzzdeee** [comment]
Since 1.4.0 now works on OpenBSD, can confirm I have it now as well.
