### ISSUE TITLE
Font system menu is not connected to NSFontManager 

### ISSUE THREAD

**Issue by onflapp** [gnustep/apps-gorm#8]
NSFontManager needs to have access to system's Font menu so that it can manage menu items based on current selection (e.g. setting "bold" or "unbold")
This can be either be done by letting NSFontManager to create system Font menu or be assigning Fonts menu to NSFontManager programmatically.

When NSFontManager and Font menu are both created by Gorm, there is no way how one can connect the Fonts menu to the NSFontManager. 
NSFontManager shows "menu" as outlet but as it is impossible to select NSMenu itself (only NSMenuItem can be selected), the connection cannot be done manually.

Alternative approach could be to simply find Font system menu at runtime and assign it to NSFontManager (I believe that's what NextStep and Mac OS does).

**Comment by gcasa** [comment]
1) Start Gorm
2) Create a new Application
3) Go to the menu palette
4) Drag the Font menu into the menu
5) go to the inspector, select Connections
6) Open the Font menu, click on each menu item to see the connection

RESULT: You should see everything connected to (NSFont) the font manager.

What are you referring to?   All of these items are connected to the Font Manager.   Are you talking about connections FROM the font manager to the menus?

**Comment by gcasa** [comment]
Also, you can connect NSFont to the menu.   I believe GNUstep might do this automatically when the model is loaded, but I am not sure.  I will double-check.

**Comment by onflapp** [comment]
`[NSFontManager fontMenu] ` is not connected to the font menu.
This means that NSFontManager is not able to change menu actions (e.g. bold) based on current selection.

**Comment by gcasa** [comment]
This should now be fixed... PLEASE test and let me know.  Re-open this issue if it doesn't work.

**Comment by onflapp** [comment]
@gcasa unfortunately it doesn't seem to work for me. 
Should the connection happen at runtime (Gorm file is loaded) or should this happen only once when I add the Font menu?

**Comment by gcasa** [comment]
My fix was so that when you drag the font menu in it makes the connection automatically.  This will not effec existing gorm files.  You need to make this connection manually for any preexisting files.   My apologies for my late reply.
